name: photonmap
channels:
  - conda-forge
  - fredboudon
  - defaults
dependencies:
  - python=3.10
  - pybind11
  - pytest
  - embree3
  - make
  - cxx-compiler
  - cmake
  - tbb
  - tbb-devel
  - boost
  - openmp
  - openalea.lpy
  - scipy
