name: photonmap
channels:
  - conda-forge
  - openalea3
dependencies:
  - python
  - jupyterlab
  - jupyter-packaging
  - ipywidgets
  - openalea.lpy
  - openalea.plantgl
  - pybind11
  - pytest
  - embree
  - pandas
  - openpyxl
  - make
  - cxx-compiler
  - cmake
  - tbb
  - tbb-devel
  - boost
  - llvm-openmp
  - openalea.lpy
  - scipy
  - matplotlib
  - pip
  - sphinx
  - sphinx-autoapi
  - sphinx-copybutton
  - nbsphinx
  - sphinx_rtd_theme