channels:
  - conda-forge
  - openalea3
dependencies:
  - python
  - jupyterlab
  - jupyter-packaging
  - ipywidgets
  - openalea.lpy
  - openalea.plantgl
  - oawidgets
  - pybind11
  - pytest
  - embree
  - pandas
  - make
  - cxx-compiler
  - cmake
  - tbb
  - tbb-devel
  - llvm-openmp
  - vs2022_win-64 # [win]
  - scipy
  - matplotlib
  - pip
  - sphinx
  - sphinx-autoapi
  - sphinx-copybutton
  - nbsphinx
  - pydata-sphinx-theme
  - openpyxl
  - myst-parser
  - sphinx-favicon
  - scikit-build
  - scikit-build-core
