package:
  name: openalea.spice
  version: "0.1.0"

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True

requirements:
  host:
    - python x.x
    - numpy x.x
    - pybind11-abi
    - scikit-build-core
    - scipy

  build:
    - {{ compiler("cxx") }}
    - python x.x
    - numpy x.x
    - scikit-build-core
    - scipy
    - make
    - cmake
    - vs2022_win-64 # [win]
    - ninja
    - pybind11
    - embree
    - llvm-openmp
    - tbb
    - tbb-devel

  run:
    - python x.x
    - numpy x.x
    - jupyterlab
    - openalea.plantgl
    - openalea.lpy
    - oawidgets
    - ipywidgets
    - pandas
    - embree
    - matplotlib
    - pywin32 [win]

test:
  imports:
    - openalea.spice
    - openalea.spice.common
    - openalea.spice.energy
    - openalea.spice.loader
    - openalea.spice.reader
    - openalea.spice.simulator
  requires:
    - pytest
  source_files:
    - tests/**
  commands:
    - pytest

about:
  home: https://github.com/openalea-incubator/photon_mapping
