package:
  name: openalea.photonmap
  version: "0.1.0"

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: photonmap
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python x.x
    - pybind11-abi
    - scikit-build-core
    - numpy
    - scipy

  build:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
    - python x.x
    - scikit-build-core
    - numpy x.x
    - scipy
    - make
    - cmake
    - pybind11
    - embree
    - llvm-openmp
    - tbb
    - tbb-devel

  run:
    - python x.x
    - numpy x.x
    - jupyterlab
    - jupyter-packaging
    - oawidgets
    - ipywidgets
    - pandas
    - matplotlib
    - pywin32 [win]

test:
  imports:
    - openalea.photonmap
    - openalea.photonmap.common
    - openalea.photonmap.energy
    - openalea.photonmap.loader
    - openalea.photonmap.reader
    - openalea.photonmap.simulator
  requires:
    - pytest
  source_files:
    - tests/**
  commands:
    - pytest

about:
  home: https://github.com/openalea-incubator/photon_mapping
