# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import sys

sys.path.insert(0, os.path.abspath("../.."))

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",  # support for automatic inclusion of docstring
    "sphinx.ext.autosummary",  # generates autodoc summaries
    "sphinx.ext.doctest",  # inclusion and testing of doctest code snippets
    "sphinx.ext.intersphinx",  # support for linking to other projects
    "sphinx.ext.imgmath",  # support for math equations
    "sphinx.ext.ifconfig",  # support for conditional content
    "sphinx.ext.viewcode",  # support for links to source code
    "sphinx.ext.coverage",  # includes doc coverage stats in the documentation
    "sphinx.ext.todo",  # support for todo items
    "sphinx.ext.napoleon",  # support for numpy and google style docstrings
    "sphinx_favicon",  # support for favicon
    "nbsphinx",  # for integrating jupyter notebooks
    "myst_parser",  # for parsing .md files
]

templates_path = ["_templates"]
autosummary_generate = True
exclude_patterns = ["_build", "_templates"]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"
# General information about the project.
project = "openalea.spice"
copyright = "Cecill-C INRAE / INRIA / CIRAD"
author = "Tuan-Minh NGUYEN, Aurélien BESNIER"
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "0.1"
# The full version, including alpha/beta/rc tags.
release = "0.1.0"
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"
# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


autoapi_dirs = ["../../src/openalea"]
# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "pydata_sphinx_theme"
html_theme_options = {
    "header_links_before_dropdown": 6,
    "sidebarwidth": 200,
    "collapse_navigation": False,
    "show_toc_level": 2,
    "navigation_depth": 2,
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/openalea-incubator/photon_mapping",
            "icon": "fa-brands fa-github",
        },
    ],
    "show_version_warning_banner": True,
    "footer_start": ["copyright"],
    "footer_center": ["sphinx-version"],
    "sidebar_includehidden" : True,
    "secondary_sidebar_items": ["page-toc", "edit-this-page", "sourcelink"],
}
html_static_path = ["_static"]
html_logo = "_static/openalea_web.svg"
html_favicon = "_static/openalea_web.svg"
# If false, no module index is generated.
html_domain_indices = True
# If false, no index is generated.
html_use_index = True
# If true, the index is split into individual pages for each letter.
html_split_index = False
# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True
# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = True
# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

nbsphinx_thumbnails = {
    "examples/plantgl-rad-scene/PlantRadScene": "_static/PlantRadScene.png",
}

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {}
latex_documents = [
    (
        master_doc,
        "openalea.spice.tex",
        "openalea.spice Documentation",
        "INRA / INRIA / CIRAD",
        "manual",
    ),
]

# -- Options for manual page output ---------------------------------------
# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "openalea.spice", "openalea.spice Documentation", [author], 1)
]

# -- Options for Texinfo output -------------------------------------------
# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "openalea.spice",
        "openalea.spice Documentation",
        author,
        "openalea.spice",
        "Photon mapping with python wrapper.",
        "Miscellaneous",
    ),
]
