name: Python Package using Conda

on: [push]

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
          
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
      max-parallel: 5
      
    environment: anaconda_build
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Setup conda
      run: |
        # Setup conda
        sudo conda config --set always_yes yes
        sudo conda config --set remote_read_timeout_secs 600
        sudo conda config --set auto_update_conda False
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name photonmap
        conda activate photonmap
        conda install clang
    - name: build
      run: |
        export CC=/usr/share/miniconda/envs/photonmap/bin/clang CXX=/usr/share/miniconda/envs/photonmap/bin/clang++
        python3 -m pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
